steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-00-ca3094ed65a8/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s

options:
  pool:
    name: 'projects/qwiklabs-gcp-00-ca3094ed65a8/locations/europe-north1/workerPools/SALE'  
    
